name: Test Cache Lab

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential python3
    
    - name: Build csim
      id: build-csim
      run: make csim
      continue-on-error: true
      
    - name: Build ctuner  
      id: build-ctuner
      run: make ctuner
      continue-on-error: true
      
    - name: Test csim
      if: steps.build-csim.outcome == 'success'
      run: make test-csim
      continue-on-error: true
      
    - name: Test ctuner
      if: steps.build-ctuner.outcome == 'success'
      run: make test-ctuner
