name: Test Cache Lab

on: [push, pull_request]

jobs:
  test-csim:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential python3
    - name: Build csim
      run: make csim
    - name: Test csim
      run: make test-csim

  test-ctuner:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential python3
    - name: Build ctuner
      run: make ctuner
    - name: Test ctuner
      run: make test-ctuner

  submission:
    runs-on: ubuntu-latest
    needs: [test-csim, test-ctuner]
    if: success()
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    - name: Push submission files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        cp csim.c /tmp/csim.c
        cp ctuner.c /tmp/ctuner.c
        cp Makefile /tmp/Makefile
        git checkout --orphan submission
        git rm -rf .
        cp /tmp/csim.c csim.c
        cp /tmp/ctuner.c ctuner.c
        cp /tmp/Makefile Makefile
        git add csim.c ctuner.c Makefile
        git commit -m "Submission files after successful tests"
        git push origin submission --force